name: Fireup Main
slug: fireup_main
version: "1.0"
description: "An add-on that runs the Selenium-based fireup_main script."
startup: application
boot: auto
arch:
  - amd64
  - armv7
  - aarch64
options: {}
schema: {}
